sonar.projectKey=${env.SONAR_PROJECT_KEY}
sonar.organization=${env.SONAR_ORGANIZATION_KEY}

sonar.projectName=learnKubernetes
sonar.sources=.
sonar.exclusions=**/vendor/**,**/*.pb.go,**/lib/events/**,**/lib/rmq/**,**/lib/types/**,**/broker/**

# Tells sonar where the test files live
sonar.tests=.
sonar.test.inclusions=**/*_test.go
# Used as I have a mono repo with various repos that tests are run under.
# This allows sonar to find the coverage out files per repo.
sonar.go.coverage.reportPaths=**/coverage.out
