apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          # --- MANDATORY FOR apt-get TO WORK ---
          # securityContext:
          #   runAsUser: 0
          ports:
            - containerPort: 27017
          envFrom:
            - secretRef:
                name: mongo-secret
            - configMapRef:
                name: mongo-config
          # lifecycle:
          #   postStart:
          #     exec:
          #       command:
          #         - /bin/sh
          #         - -c
          #         - >
          #           if ! command -v mongoimport &> /dev/null; then
          #             apt-get update && apt-get install -y mongodb-database-tools;
          #           fi;
          #           sleep 5;
          #           mongoimport --host localhost \
          #           --username $(MONGO_INITDB_ROOT_USERNAME) \
          #           --password $(MONGO_INITDB_ROOT_PASSWORD) \
          #           --authenticationDatabase admin \
          #           --db test --collection users --type json --file /data/init/initDb.json --jsonArray --upsert
          volumeMounts:
            - name: init-data-volume
              mountPath: /data/init # Where the JSON file sits
            - name: mongo-storage # Where the actual DB lives
              mountPath: /data/db
      volumes:
        - name: init-data-volume
          configMap:
            name: mongo-init-data # The JSON from your script
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc # The persistent storage
---
# SERVICE: Request comes in on port 80 and is forwarded to 27017
apiVersion: v1
kind: Service
metadata:
  name: mongo-service # MAPS TO THE CONFIG-MAP
spec:
  selector: # SELECTS PODS TO FORWARD TO REQ TO
    app: mongo
  ports:
    - protocol: TCP
      port: 27017 # THE IP OF THE SERVICE WITHIN THE CLUSTER. STANDARD IS USE SAME PORT AS POD
      targetPort: 27017 # PORT OF THE PODS THAT BELONG TO THE SERVICE. TARGET_PORT MUST === CONTAINER_PORT
