apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-deployment
  labels:
    app: mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      initContainers:
        - name: mqtt-init
          image: mqtt-init-container-app:v1
          imagePullPolicy: Never
          securityContext:
            runAsUser: 0 # Must be root to change file ownership
            runAsGroup: 0
          env:
            - name: MQTT_USER
              valueFrom:
                secretKeyRef:
                  name: mqtt-secret
                  key: MQTT_USER
            - name: MQTT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mqtt-secret
                  key: MQTT_PASSWORD
          volumeMounts:
            - name: shared-config
              mountPath: /mosquitto/auth/ #/mosquitto/config
            - name: mqtt-data
              mountPath: /mosquitto/data
      containers:
        - name: mqtt
          image: eclipse-mosquitto:latest
          imagePullPolicy: Always
          # Defines the privelege and access level for the container.
          securityContext:
            # Tells Linux Kernel inside the node to run the containers process as UID (User ID) 1883 and GID 1883 (Group ID) instead of default 0 or root
            runAsUser: 1883
            runAsGroup: 1883
          ports:
            - containerPort: 1883
            - containerPort: 8883
          volumeMounts:
            # Mounts the static config file from your ConfigMap
            - name: config-v
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
            # Mounts the password_file GENERATED by the Init Container
            - name: shared-config
              mountPath: /mosquitto/auth/password_file #/mosquitto/config/password_file
              subPath: password_file
            - name: mqtt-data
              mountPath: /mosquitto/data/

          livenessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        # Static configuration
        - name: config-v
          configMap:
            name: mosquitto-config
        # The shared "bridge" between Go and Mosquitto
        - name: shared-config
          # THIS ALLOWS YOU TO SHARE A FILE BETWEEN 2 CONTAINERS.
          # When the pod starts it crates an empty dir. The InitContainer mounts that foler and the Go code writes to that dir.
          # The container mounts that folder and because its on the same physical space on disk it can access that folder.
          emptyDir: {}
        # Persistent storage for messages/sessions
        - name: mqtt-data
          persistentVolumeClaim:
            claimName: mqtt-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-service
spec:
  type: ClusterIP
  selector:
    app: mqtt
  ports:
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
    - name: mqtt-tls
      protocol: TCP
      port: 8883
      targetPort: 8883
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt2-deployment
  labels:
    app: mqtt2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt2
  template:
    metadata:
      labels:
        app: mqtt2
    spec:
      initContainers:
        - name: mqtt-init
          image: mqtt-init-container-app:v1
          imagePullPolicy: Never
          securityContext:
            runAsUser: 0 # Must be root to change file ownership
            runAsGroup: 0
          env:
            - name: MQTT_USER
              valueFrom:
                secretKeyRef:
                  name: mqtt-secret
                  key: MQTT_USER
            - name: MQTT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mqtt-secret
                  key: MQTT_PASSWORD
          volumeMounts:
            - name: shared-config
              mountPath: /mosquitto/auth/ #/mosquitto/config
            - name: mqtt-data
              mountPath: /mosquitto/data
      containers:
        - name: mqtt2
          image: eclipse-mosquitto:latest
          imagePullPolicy: Always
          # Defines the privelege and access level for the container.
          securityContext:
            # Tells Linux Kernel inside the node to run the containers process as UID (User ID) 1883 and GID 1883 (Group ID) instead of default 0 or root
            runAsUser: 1883
            runAsGroup: 1883
          ports:
            - containerPort: 1883
            - containerPort: 8883
          volumeMounts:
            # Mounts the static config file from your ConfigMap
            - name: config-v
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
            # Mounts the password_file GENERATED by the Init Container
            - name: shared-config
              mountPath: /mosquitto/auth/password_file #/mosquitto/config/password_file
              subPath: password_file
            - name: mqtt-data
              mountPath: /mosquitto/data/

          livenessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        # Static configuration
        - name: config-v
          configMap:
            name: mosquitto-config
        # The shared "bridge" between Go and Mosquitto
        - name: shared-config
          # THIS ALLOWS YOU TO SHARE A FILE BETWEEN 2 CONTAINERS.
          # When the pod starts it crates an empty dir. The InitContainer mounts that foler and the Go code writes to that dir.
          # The container mounts that folder and because its on the same physical space on disk it can access that folder.
          emptyDir: {}
        # Persistent storage for messages/sessions
        - name: mqtt-data
          persistentVolumeClaim:
            claimName: mqtt2-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt2-service
spec:
  type: ClusterIP
  selector:
    app: mqtt2
  ports:
    - name: mqtt2
      protocol: TCP
      port: 1883
      targetPort: 1883
    - name: mqtt2-tls
      protocol: TCP
      port: 8883
      targetPort: 8883
