name: Build and Test Application
env:
  PREFIX: ${{ github.event_name == 'push' && "latest" || "pr" }}
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      ["master", "feature/*", "bugfix/*", "release/*", "!poc/*", "!test/*"]
jobs:
  set_up_and_test:
    name: Set Up Go Install Dependencies and Run Unit Tests
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./scripts
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.work"
          cache-dependency-path: "**/*.sum" # Caches all sub-module dependencies
      - name: Install Dependencies
        working-directory: ./scripts
        run: |
          chmod +x ./setUp.sh
          ./setUp.sh
      - name: Run Unit Tests
        working-directory: ./scripts
        run: |
          chmod +x ./runTests.sh
          ./runTests.sh
  build_and_publish_docker_images:
    name: Build and Publish Docker Images For All Services
    runs-on: ubuntu-latest
    needs: set_up_and_test
    # A Strategy and Matrix allows you to run multiple variations of a single job simultaneously without duplicating the YAML code.
    # Strategy: A job settings that tells GithubActions how to handle multiple concurrent executions.
    # Matrix: A sub property of Strategy that allows for configuration of the runs. Each configured run is treated as a seperate job.
    # You can specify any key value pair in the matrix list and use them in the steps as needed.
    strategy:
      matrix:
        include:
          - service: "app-gateway"
            image_name: "app-gateway"
            dockerfile: "app-gateway/Dockerfile"
            version_file: "app-gateway/version.txt"
            pass_tailwind: true
          - service: "app-users"
            image_name: "app-users"
            dockerfile: api/users/Dockerfile
            version_file: api/users/version.txt
            pass_tailwind: true
    steps:
      - name: Check out the repository to the runner
        # Uses: This tells GA to download and execute a reusable workflow block (Action).
        # actions/checkout: This referes to the path to the actual repo being used.
        # @v6: This is the version of that repo being used. So essentially this downloads the repo and executes it.
        # These tags/extensions are found: https://github.com/marketplace?type=actions
        uses: actions/checkout@v6
      - name: Read Service apiVersion
        id: get_version
        run: |
          VERSION=$(cat ${{ matrix.version_file }})
          echo "version=v${VERSION}" >> $GITHUB_OUTPUT
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Generate Docker Metadata & Tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: mfduar8766/${{ matrix.image_name }}
          tags: |
            type=raw,value=${{ env.PREFIX }}_version_${{ steps.get_version.outputs.version }}_commit_{{sha}}_timestamp_{{date 'YYYY_MM_DD_time_HH_mm_ss'}}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            ${{ matrix.pass_tailwind && 'TAIL_WIND_VRSION=4.2.2' || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # This is manually using a bash script to do the docker build and push for all services.
  # The above job is using a matrix to build and push docker images for all services.
  # The below job is commented out because it is not needed anymore.
  # build_docker_images:
  #   name: Build Docker Images For All Services
  #   runs-on: ubuntu-latest
  #   needs: set_up_and_test
  #   steps:
  #     - name: Check out the repository to the runner
  #       uses: actions/checkout@v6
  #     - name: Build Docker Images
  #       working-directory: ./scripts
  #       run: |
  #         chmod +x ./buildDockerImages.sh
  #         ./buildDockerImages.sh
