name: Build and Test Application
env:
  PREFIX: ${{ github.event_name == 'push' && 'latest' || 'pr' }}
  TAIL_WIND_VRSION: 4.2.2
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      ["master", "feature/*", "bugfix/*", "release/*", "!poc/*", "!test/*"]
# Cancle previous run if another commit is pushed while in progress.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Cancel in-progress runs ONLY on Pull Requests / feature branches, not on master.
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}
jobs:
  set_up_and_test:
    name: Set Up Go, Install Dependencies, and Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.work"
          cache-dependency-path: "**/*.sum"

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Tooling
        run: |
          go install github.com/vektra/mockery/v3@v3.7.3
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      # 1. First, build proto files so generated code exists
      - name: Generate Protobufs
        run: |
          if [ -f "./lib/protos/build.sh" ]; then
            cd ./lib/protos && chmod +x build.sh && ./build.sh
          fi

      # 2. Second, generate mocks in lib and api/users so mock packages exist
      - name: Generate Mocks
        run: |
          (cd lib && mockery)
          (cd api/users && mockery)
          (cd app-gateway && mockery)

      # 3. Third, update Go workspace & go mod tidy (now all mock files exist!)
      - name: Update Go Workspace
        run: |
          chmod +x ./scripts/updateGoWork.sh
          ./scripts/updateGoWork.sh

      # 4. Finally, run tests
      - name: Run Unit Tests
        run: |
          chmod +x ./scripts/runTests.sh
          ./scripts/runTests.sh
  sonar_scan:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        # https://github.com/SonarSource/sonarqube-scan-action
        uses: SonarSource/sonarqube-scan-action@v8.2.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORGANIZATION_KEY: ${{ secrets.SONAR_ORGANIZATION_KEY }}
      # This step checks the Quality Gate result and FAILS the GitHub job if coverage/quality is below threshold
      - name: SonarQube Quality Gate Check
        uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORGANIZATION_KEY: ${{ secrets.SONAR_ORGANIZATION_KEY }}
  build_and_publish_docker_images:
    name: Build and Publish Docker Images For All Services
    runs-on: ubuntu-latest
    needs: set_up_and_test
    # A Strategy and Matrix allows you to run multiple variations of a single job simultaneously without duplicating the YAML code.
    # Strategy: A job settings that tells GithubActions how to handle multiple concurrent executions.
    # Matrix: A sub property of Strategy that allows for configuration of the runs. Each configured run is treated as a seperate job.
    # You can specify any key value pair in the matrix list and use them in the steps as needed.
    strategy:
      matrix:
        include:
          - service: "app-gateway"
            image_name: "app-gateway"
            dockerfile: "app-gateway/Dockerfile"
            version_file: "app-gateway/version.txt"
            pass_tailwind: true
          - service: "app-users"
            image_name: "app-users"
            dockerfile: api/users/Dockerfile
            version_file: api/users/version.txt
            pass_tailwind: true
          - service: "app-mqtt"
            image_name: "app-mqtt"
            dockerfile: initContainers/mqttInitContainer/Dockerfile
            version_file: initContainers/mqttInitContainer/version.txt
            pass_tailwind: false
    steps:
      - name: Check out the repository to the runner
        # Uses: This tells GA to download and execute a reusable workflow block (Action).
        # actions/checkout: This referes to the path to the actual repo being used.
        # @v6: This is the version of that repo being used. So essentially this downloads the repo and executes it.
        # These tags/extensions are found: https://github.com/marketplace?type=actions
        uses: actions/checkout@v6
      - name: Read Service apiVersion
        id: get_version
        run: |
          VERSION=$(cat ${{ matrix.version_file }})
          echo "version=v${VERSION}" >> $GITHUB_OUTPUT
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Generate Docker Metadata & Tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}
          tags: |
            type=raw,value=${{ env.PREFIX }}_version_${{ steps.get_version.outputs.version }}_commit_{{sha}}_timestamp_{{date 'YYYY_MM_DD_time_HH_mm_ss'}}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags:
            ${{ steps.meta.outputs.tags }}
            # Does not support nested expressions: ${{ ... ${{ }} }} so need to concat the strings.
            # Nested Example: ${{ matrix.pass_tailwind && 'TAIL_WIND_VRSION=${{ env.TAIL_WIND_VRSION }}' || '' }}
            # Or add the env as a property on the matrix its self.
          build-args: |
            ${{ matrix.pass_tailwind && format('TAIL_WIND_VRSION={0}', env.TAIL_WIND_VRSION) || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # This is manually using a bash script to do the docker build and push for all services.
  # The above job is using a matrix to build and push docker images for all services.
  # The below job is commented out because it is not needed anymore.
  # build_docker_images:
  #   name: Build Docker Images For All Services
  #   runs-on: ubuntu-latest
  #   needs: set_up_and_test
  #   steps:
  #     - name: Check out the repository to the runner
  #       uses: actions/checkout@v6
  #     - name: Build Docker Images
  #       working-directory: ./scripts
  #       run: |
  #         chmod +x ./buildDockerImages.sh
  #         ./buildDockerImages.sh
