name: Run Cron Jobs

on:
  schedule:
    # Minute, Hour, DayOfMonth, Month, DayOfTheWeek
    - cron: "*/5 * * * *"
  # Allows you to manually trigger the job fom the actions tab.
  workflow_dispatch:

jobs:
  vulnerability_scan:
    name: Security Scan
    strategy:
      matrix:
        module:
          [
            "lib",
            "app-gateway",
            "api/users",
            "initContainers/mqttInitContainer",
          ]
    uses: ./.github/workflows/vulnerabilityScan.yaml
    with:
      module_dir: ${{ matrix.module }}
