on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      ["master", "feature/*", "bugfix/*", "release/*", "!poc/*", "!test/*"]
jobs:
  set_up_and_test:
    name: "Set Up Go Install Dependencies & Run Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.work"
          cache-dependency-path: "**/*.sum" # Caches all sub-module dependencies
      - name: Install Dependencies
        working-directory: ./scripts
        run: |
          chmod +x ./setUp.sh
          ./setUp.sh
            - name: Run Unit Tests

  # run-tests:
  #   name: Run Unit Tests
  #   runs-on: ubuntu-latest
  #   needs: set_up
  #   # defaults:
  #   #   run:
  #   #     working-directory: ./scripts
  #   steps:
  #     # - name: Check out the repository to the runner
  #     #   uses: actions/checkout@v6
  #     # - name: Set up Go
  #     #   uses: actions/setup-go@v5
  #     #   with:
  #     #     go-version-file: "go.work"
  #     #     cache-dependency-path: "**/*.sum" # Caches all sub-module dependencies
  #     # - name: Install Dependencies
  #     #   working-directory: ./scripts
  #     #   run: |
  #     #     chmod +x ./setUp.sh
  #     #     ./setUp.sh
  #     - name: Run Unit Tests
  #       working-directory: ./scripts
  #       run: |
  #         chmod +x ./runTests.sh
  #         ./runTests.sh
