apiVersion: v1
kind: Secret
metadata:
  name: rmq-secret
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: "dXNlcg=="
  RABBITMQ_DEFAULT_PASS: "cGFzc3dvcmQ="
  RABBITMQ_USER: "dXNlcg=="
  RABBITMQ_PASS: "cGFzc3dvcmQ="
  RABBITMQ_USERS_QUEUE: "dXNlcnNfcXVldWU="
